name: Build and Push Docker Image

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: docker-react-mywebsite-i

jobs:
  build-and-push:
    runs-on: node:14-alpine

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Build Docker image
      run: docker-compose build -t $IMAGE_NAME

    - name: Push Docker image to Docker Hub
      run: docker-compose push $IMAGE_NAME